### PR TITLE
Update to minecraft 1.15.x

### PR DESCRIPTION
**Pull request by ashpieboop**
This is a basic update of the mod for 1.15.x

There might be more work to do, although I also made a [project restructuring](https://github.com/ArisuOngaku/FOML/tree/test-mod-separation) based on this pr's branch to separate the mod and test mod in different subprojects.

### CODE REVIEW

**Comment by ArisuOngaku** [comment]
Btw if you want I can  this project maintenance.

**Comment by ashpieboop** [comment]
Btw if you want I can handle this project's maintenance.

**Comment by ashpieboop** [comment]
Also, is this supposed to be this size?
image

**Comment by alothmanmoe** [comment]
> 
> 
> Also, is this supposed to be this size?
> image

Sizing of obj models cant really be determined well when modeling, so i had planned to add a transform and scale options to the json file so users could configure it themselvs but never got around to it.
If you're willing to continue maintaining the project i wouldn't mind, just send me a message on discord.

**Review by alothmanmoe — APPROVED** [review]

**Pull request merged**
